repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-json
      - id: check-xml
      - id: check-yaml
        files: \.(yaml|yml)$

  - repo: https://github.com/digitalpulp/pre-commit-php.git
    rev: 1.4.0
    hooks:
      - id: php-lint

  - repo: https://github.com/luis-knd/pre-commit
    rev: v0.0.2
    hooks:
      - id: install-dependencies
      - id: phpcbf-subdir
        args: [
          'app/..',
          '--extensions=php',
          '--standard=PSR12',
          '--ignore= vendor, storage, bootstrap, resources, tests, public, config, app/Helpers/helpers, bin',
          'app/..'
        ]
      - id: phpcs-subdir
        args: [
          'app/..',
          '--report=code',
          '--colors',
          '--report-width=80',
          '--standard=PSR12',
          '--ignore= vendor, storage, bootstrap, resources, tests, public, config, app/Helpers/helpers, bin'
        ]
      - id: phpstan-subdir
        args: ['app/..']
        files: ^.*\.(php)$

  - repo: local
    hooks:
      # PHPUnit Hook for Backend Testing
      - id: phpunit
        name: Test Backend with PhpUnit
        entry: >
          bash -c 'output=$(docker-compose run --rm artisan test);
                   if echo "$output" | grep -q "FAILED"; then
                     endPosition=$(echo "$output" | grep "FAILED" -A 50 | cut -d: -f1);
                     echo -e "${endPosition}";
                     exit 1;
                   else
                     exit 0;
                   fi'
        language: system
        files: ^tests/.*\.(php)$
        pass_filenames: false

